# Generated by Django 3.0.7 on 2020-06-15 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SugestaoFaculdade',
            fields=[
                ('idsugestao_faculdade', models.IntegerField(db_column='idSugestao_Faculdade', primary_key=True, serialize=False)),
                ('sugestao', models.CharField(blank=True, max_length=45, null=True)),
                ('titulo', models.CharField(blank=True, max_length=45, null=True)),
                ('relevancia', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'db_table': 'Sugestao_Faculdade',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TopicoFaculdade',
            fields=[
                ('idtopico_faculdade', models.IntegerField(db_column='idTopico_Faculdade', primary_key=True, serialize=False)),
                ('topico', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'Topico_Faculdade',
                'managed': False,
            },
        ),
    ]
