# Generated by Django 3.0.7 on 2020-06-15 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('idaula', models.IntegerField(db_column='idAula', primary_key=True, serialize=False)),
                ('dia_horario', models.DateTimeField(blank=True, null=True)),
                ('tipo_aula', models.CharField(blank=True, max_length=8, null=True)),
                ('tema', models.CharField(blank=True, max_length=45, null=True)),
                ('descricao', models.CharField(blank=True, max_length=45, null=True)),
                ('enttime', models.DateTimeField(blank=True, db_column='entTime', null=True)),
                ('is_aberta', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Aula',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Excursao',
            fields=[
                ('idexcursao', models.IntegerField(db_column='idExcursao', primary_key=True, serialize=False)),
                ('nome_local', models.CharField(blank=True, max_length=45, null=True)),
                ('objetivo', models.CharField(blank=True, max_length=45, null=True)),
                ('atividade', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'Excursao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Prova',
            fields=[
                ('idprova', models.IntegerField(db_column='idProva', primary_key=True, serialize=False)),
                ('descricao_conteudo', models.CharField(blank=True, max_length=45, null=True)),
                ('quant_questao', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'Prova',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Teorica',
            fields=[
                ('idteorica', models.IntegerField(db_column='idTeorica', primary_key=True, serialize=False)),
                ('conteudo', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'Teorica',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TrabalhoPratico',
            fields=[
                ('idtrabalho_pratico', models.IntegerField(db_column='idTrabalho_Pratico', primary_key=True, serialize=False)),
                ('link_documentacao', models.CharField(blank=True, max_length=45, null=True)),
                ('quant_membros_grupo', models.CharField(blank=True, max_length=45, null=True)),
                ('desenvolvimento_esperado', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'Trabalho_Pratico',
                'managed': False,
            },
        ),
    ]
