# Generated by Django 3.0.7 on 2020-06-15 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aluno', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacoes',
            fields=[
                ('aluno_idaluno', models.OneToOneField(db_column='Aluno_idAluno', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='aluno.Aluno')),
                ('end_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Avaliacoes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Caracteristica',
            fields=[
                ('idcaracteristica', models.IntegerField(db_column='idCaracteristica', primary_key=True, serialize=False)),
                ('qualificacao', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'Caracteristica',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Perguntas',
            fields=[
                ('idperguntas', models.IntegerField(db_column='idPerguntas', primary_key=True, serialize=False)),
                ('questao', models.CharField(blank=True, max_length=45, null=True)),
                ('tipo_aula', models.CharField(blank=True, max_length=8, null=True)),
            ],
            options={
                'db_table': 'Perguntas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Respostas',
            fields=[
                ('idrespostas', models.IntegerField(db_column='idRespostas', primary_key=True, serialize=False)),
                ('aberta', models.IntegerField(blank=True, null=True)),
                ('resposta', models.CharField(blank=True, max_length=4, null=True)),
                ('resposta_aberta', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'Respostas',
                'managed': False,
            },
        ),
    ]
