# Generated by Django 3.0.7 on 2020-06-15 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('idaluno', models.IntegerField(db_column='idAluno', primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=45, null=True)),
                ('username', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=45)),
                ('login', models.CharField(blank=True, max_length=45, null=True)),
                ('senha', models.CharField(max_length=45)),
                ('matricula', models.CharField(max_length=45)),
                ('xp', models.DecimalField(blank=True, db_column='XP', decimal_places=0, max_digits=20, null=True)),
            ],
            options={
                'db_table': 'Aluno',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Elo',
            fields=[
                ('idelo', models.IntegerField(db_column='idElo', primary_key=True, serialize=False)),
                ('tipo', models.CharField(blank=True, db_column='Tipo', max_length=7, null=True)),
            ],
            options={
                'db_table': 'Elo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SugestaoCurso',
            fields=[
                ('idsugestao_curso', models.IntegerField(db_column='idSugestao_Curso', primary_key=True, serialize=False)),
                ('sugestao', models.CharField(blank=True, max_length=45, null=True)),
                ('titulo', models.CharField(blank=True, max_length=45, null=True)),
                ('relevancia', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'db_table': 'Sugestao_Curso',
                'managed': False,
            },
        ),
    ]
