# Generated by Django 3.0.7 on 2020-06-15 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('idcurso', models.IntegerField(db_column='idCurso', primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=45, null=True)),
                ('codigo', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'Curso',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('iddisciplina', models.IntegerField(db_column='idDisciplina', primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'Disciplina',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TopicoSugestaoCurso',
            fields=[
                ('idtopico_sugestao_curso', models.IntegerField(db_column='idTopico_Sugestao_Curso', primary_key=True, serialize=False)),
                ('topico', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'Topico_Sugestao_Curso',
                'managed': False,
            },
        ),
    ]
