# Generated by Django 3.0.7 on 2020-06-15 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aluno', '0001_initial'),
        ('professor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlunoHasTurma',
            fields=[
                ('aluno_idaluno', models.OneToOneField(db_column='Aluno_idAluno', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='aluno.Aluno')),
            ],
            options={
                'db_table': 'Aluno_has_Turma',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DiasFixos',
            fields=[
                ('iddias_fixos', models.IntegerField(db_column='idDias_Fixos', primary_key=True, serialize=False)),
                ('dia', models.CharField(blank=True, max_length=3, null=True)),
                ('horario', models.DateTimeField(blank=True, null=True)),
                ('sala', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'Dias_Fixos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProfessorHasTurma',
            fields=[
                ('professor_idprofessor', models.OneToOneField(db_column='Professor_idProfessor', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='professor.Professor')),
            ],
            options={
                'db_table': 'Professor_has_Turma',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SugestaoTurma',
            fields=[
                ('idsugestao_turma', models.IntegerField(db_column='idSugestao_Turma', primary_key=True, serialize=False)),
                ('sugestao', models.CharField(blank=True, max_length=45, null=True)),
                ('titulo', models.CharField(blank=True, max_length=45, null=True)),
                ('relevancia', models.CharField(blank=True, max_length=15, null=True)),
                ('sugestao_turmacol', models.CharField(blank=True, db_column='Sugestao_Turmacol', max_length=45, null=True)),
            ],
            options={
                'db_table': 'Sugestao_Turma',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TopicaTurma',
            fields=[
                ('idtopica_turma', models.IntegerField(db_column='idTopica_Turma', primary_key=True, serialize=False)),
                ('topico', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'Topica_Turma',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('idturma', models.IntegerField(db_column='idTurma', primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=45, null=True)),
                ('codigo', models.CharField(blank=True, max_length=45, null=True)),
                ('ano', models.CharField(blank=True, max_length=45, null=True)),
                ('semestre', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'Turma',
                'managed': False,
            },
        ),
    ]
